# Original game for the atlas testbed (30.08.2026) -- NOT an ARC Prize game.
# "Portals" (pt01) -- rank-2 mechanic from the Gemini round-11 pool plan:
# non-Euclidean space, breaking the Manhattan-distance prior of h(s).
#
# Rules: ACTION1-4 move the agent. Stepping onto a portal cell instantly
# relocates the agent to the SAME-COLOR twin portal elsewhere on the map.
# Reach the exit pad to complete the level. Portals are two-way and
# reusable; later levels add decoy pairs that lead away from the exit.

from arcengine import (
    ARCBaseGame,
    BlockingMode,
    Camera,
    GameAction,
    Level,
    Sprite,
)

CELL = 3
GRID = 21


# --- pixel helpers, added 03.09 by scripts/cellify_sprites.py ---------------
# These replace literal pixel indices so the sprite renders at any CELL. The
# shapes are exactly what the literals drew at CELL == 4, which
# scripts/frame_fingerprint.py verifies by hashing every frame before and
# after the rewrite.

def _fill_inner(px, color):
    """Everything except the one-pixel border."""
    for _r in range(1, CELL - 1):
        for _c in range(1, CELL - 1):
            px[_r][_c] = color
    return px


def _fill_edge(px, side, color):
    """The middle stretch of one edge -- the part that is not a corner."""
    span = range(1, CELL - 1) if CELL > 2 else range(CELL)
    for _i in span:
        if side == "top":
            px[0][_i] = color
        elif side == "bottom":
            px[CELL - 1][_i] = color
        elif side == "left":
            px[_i][0] = color
        else:
            px[_i][CELL - 1] = color
    return px


def _fill_row(px, col, color):
    """The middle rows of one column."""
    for _r in range(1, CELL - 1):
        px[_r][col] = color
    return px

WALL = 9
AGENT = 3
EXIT = 4
PORTAL_COLORS = {"1": 6, "2": 8, "3": 11}

# rows: '#'=wall, 'P'=agent, 'E'=exit, digits '1'..'3' = portal pairs
# (each digit appears exactly twice).
LEVELS = [
    # 03.09: regenerated by scripts/regen_short_levels.py on a full
    # 64x64 board (GRID 8 -> 16), nine levels along the public
    # difficulty curve. The old five levels cost 6-10 actions where the
    # public median level 1 is 30, so clearing them said nothing about
    # the games we are actually scored on -- and one of them (gv01)
    # shipped a level whose true optimum was a single action.
    # Every level below was PROVEN by BFS through the engine, never
    # counted by hand, and carries the objects of the level it replaces
    # in the same numbers.
    dict(rows=[
        '#####################',
        '#.#...........#.....#',
        '#.#####.#.###.#####.#',
        '#.#...#.#.#...#.....#',
        '#.#.#.#.#E#.###.###1#',
        '#...#.#.#.#.....#...#',
        '#####.###.#######P###',
        '#...#...#.......#...#',
        '#.#.###.#.#####.#####',
        '#.#.....#.#...#.....#',
        '#.#########.#.#####.#',
        '#.#...#.....#.......#',
        '#.###.#.#.#########.#',
        '#...#.#.#...#.#.....#',
        '###.#.#.###.#.#.#####',
        '#...#.....#.#.#.....#',
        '#.#####.###.#.#####.#',
        '#.....#.#...#.......#',
        '#####.###.###.#######',
        '#.........#.....1...#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#.#.........#.......#',
        '#.###.###.###.#####.#',
        '#...#...#.E1......#.#',
        '###.#####.#########.#',
        '#.#.#...#.#.........#',
        '#.#.#.#.#.#.#######.#',
        '#.#...#.#.#.#...#...#',
        '#.#####.###.#.#.#.###',
        '#...#...#...#.#.#.#.#',
        '#.#.#.###.###.###.#.#',
        '#.#.#.#..1#.....#.#.#',
        '#.###.#.###.###.#.#.#',
        '#.....#.#.#.#.#...#.#',
        '#.#####.#.#.#.#####.#',
        '#.....#.#...#...#...#',
        '#####.#.#.###.#.#.#.#',
        '#...#...#.#...#...#.#',
        '#.#######.#########.#',
        '#................P..#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#...#.........#....2#',
        '###.#.#.#####.#####.#',
        '#..E#.#.#...#.#.....#',
        '#.#####.#.###.#.###.#',
        '#.......#.....#.#...#',
        '#########.#####.#.###',
        '#.......#.#P....#...#',
        '###.###.#.###.#####.#',
        '#...#...#.1.#.#...#.#',
        '#1###.#####.#.###.#.#',
        '#.#...#...#.#...#...#',
        '#.#.#####.#.###.#.###',
        '#.#...#...#.#...#...#',
        '#.###.#.#.#.#.#####.#',
        '#.#.....#.#...#.....#',
        '#2#.###########.#####',
        '#.#.#...#.....#...#.#',
        '#.###.#.#.###.###.#.#',
        '#.....#.....#.......#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#.....#E...1#...#...#',
        '#####.#.#.#.#.#.#.#.#',
        '#...#.#.#.#.#.#1..#.#',
        '#.###.###.#.#.#####.#',
        '#...#.....#...#...#.#',
        '###.###########.###.#',
        '#...#.......#...#...#',
        '#.###.#####.#.#.#.###',
        '#P#...#...#...#2..#.#',
        '#.#.###.###########.#',
        '#...#.#.............#',
        '#.###.#.#######.#####',
        '#...#...#.....#.....#',
        '###.#####.###.#####.#',
        '#...#...#.#.#.....#.#',
        '#.###.#.#.#.#####.#.#',
        '#...#.#.#.#...2...#.#',
        '###.#.#.#.#.#######.#',
        '#.....#...#.........#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#...#.....#..1......#',
        '###.#####.#.#.#######',
        '#.#.#...#...#.#.....#',
        '#.#.#.#.#####.#.###.#',
        '#...#P#.#...#...#.#.#',
        '#.###.#.#.#.#.###.#.#',
        '#.....#...#.#..2..#.#',
        '###########.#######.#',
        '#.........#...#.....#',
        '#.###.#######.#.###.#',
        '#.#.#.......#.#.#.#.#',
        '#.#.#####.###.#.#.#.#',
        '#.#.....#.#...#.#...#',
        '#.#.###.#.#.###.#.###',
        '#.E.#...#.#.....#...#',
        '#####.###.#########2#',
        '#...#...#.......#.3.#',
        '#.#####.#.#######.###',
        '#.......#.1.......3.#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#...P.#.....#.......#',
        '#####.#.###.###.###.#',
        '#2..#...#.#.....#...#',
        '#.#######.#######.###',
        '#.#.......#...#...#.#',
        '#.#.###.###.#.#.###.#',
        '#.#3#.#.....#.#.#...#',
        '#.#.#.#######.#.#.#.#',
        '#.#...#...#.#...#.#1#',
        '#.###.#.#.#.#######.#',
        '#...#...#.....#.....#',
        '#.###########.#.###.#',
        '#.....1.#.....#.#.#.#',
        '#.#####.#.#####2#.#.#',
        '#...#...#.#.....#...#',
        '###.#.###.#E###.#.###',
        '#...#.....#...#.#.#.#',
        '#.#############.#.#.#',
        '#............3..#...#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#...#.#.............#',
        '###.#.#.#.#########.#',
        '#.#.#...#...#.....#.#',
        '#P#.#######.#.#.###.#',
        '#.#...#...#.#.#..3..#',
        '#.###.#.#.#.###.#####',
        '#...#...#.#..E#.....#',
        '#.#######.###.#####.#',
        '#.......#...#2..#...#',
        '#.#####.###1###.#.###',
        '#...#...#...#2.3#.#.#',
        '#####.###.###.###1#.#',
        '#.....#...#...#.#.#.#',
        '#.###.#.#####.#.#.#.#',
        '#...#.#.......#...#.#',
        '#.#.###########.###.#',
        '#.#.....#.....#.....#',
        '#.#####.#.#.#######.#',
        '#.....#...#.........#',
        '#####################',
    ]),
]


def _rect(color):
    return [[color] * CELL for _ in range(CELL)]


def _portal_px(color):
    px = [[0] * CELL for _ in range(CELL)]
    for r in range(CELL):
        for c in range(CELL):
            if (r in (0, CELL - 1) or c in (0, CELL - 1)) and (r + c) % 2 == 0:
                px[r][c] = color
    _fill_inner(px, color)
    return px


def _agent_px():
    px = [[0] * CELL for _ in range(CELL)]
    _fill_inner(px, AGENT)
    _fill_edge(px, 'top', AGENT)
    return px


def _parse(spec):
    walls, portals = set(), {}
    start = exit_cell = None
    for r, row in enumerate(spec["rows"]):
        for c, ch in enumerate(row):
            if ch == "#":
                walls.add((c, r))
            elif ch == "P":
                start = (c, r)
            elif ch == "E":
                exit_cell = (c, r)
            elif ch in PORTAL_COLORS:
                portals.setdefault(ch, []).append((c, r))
    return walls, portals, start, exit_cell


def _build_level(index, spec):
    walls, portals, start, exit_cell = _parse(spec)
    sprites = []
    for (c, r) in walls:
        sprites.append(Sprite(_rect(WALL), name=f"wall_{r}_{c}", x=c * CELL, y=r * CELL,
                              blocking=BlockingMode.PIXEL_PERFECT, tags=["sys_static"]))
    sprites.append(Sprite(_rect(EXIT), name="exit", x=exit_cell[0] * CELL, y=exit_cell[1] * CELL,
                          layer=0, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    for ch, cells in sorted(portals.items()):
        for j, (c, r) in enumerate(sorted(cells)):
            sprites.append(Sprite(_portal_px(PORTAL_COLORS[ch]), name=f"portal_{ch}_{j}",
                                  x=c * CELL, y=r * CELL, layer=1,
                                  blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    sprites.append(Sprite(_agent_px(), name="agent", x=start[0] * CELL, y=start[1] * CELL,
                          layer=3, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    return Level(sprites=sprites, grid_size=(GRID * CELL, GRID * CELL),
                 name=f"level_{index + 1}")


class Pt01(ARCBaseGame):
    def __init__(self, seed: int = 0, debug: bool = False):
        levels = [_build_level(i, spec) for i, spec in enumerate(LEVELS)]
        super().__init__(
            game_id="pt01",
            levels=levels,
            camera=Camera(width=GRID * CELL, height=GRID * CELL),
            debug=debug,
            available_actions=[1, 2, 3, 4],
            seed=seed,
        )

    def _atlas_reset_level_state(self):
        pass  # stateless beyond sprites; hook kept for harness parity

    def level_reset(self):
        super().level_reset()
        self._atlas_reset_level_state()

    def full_reset(self):
        super().full_reset()
        self._atlas_reset_level_state()

    def _sprite(self, name):
        found = self.current_level.get_sprites_by_name(name)
        return found[0] if found else None

    def step(self) -> None:
        spec = LEVELS[self.level_index]
        action = self.action.id
        if action == GameAction.RESET:
            self.complete_action()
            return
        walls, portals, start, exit_cell = _parse(spec)
        agent = self._sprite("agent")
        if agent is None:
            self.complete_action()
            return
        ac, ar = agent.x // CELL, agent.y // CELL

        if action in (GameAction.ACTION1, GameAction.ACTION2,
                      GameAction.ACTION3, GameAction.ACTION4):
            d = {GameAction.ACTION1: (0, -1), GameAction.ACTION2: (0, 1),
                 GameAction.ACTION3: (-1, 0), GameAction.ACTION4: (1, 0)}[action]
            nc, nr = ac + d[0], ar + d[1]
            if (nc, nr) not in walls and 0 <= nc < GRID and 0 <= nr < GRID:
                # portal hop: landing on a portal relocates to its twin
                for ch, cells in portals.items():
                    if (nc, nr) in cells and len(cells) == 2:
                        twin = cells[0] if cells[1] == (nc, nr) else cells[1]
                        nc, nr = twin
                        break
                agent.set_position(nc * CELL, nr * CELL)
                if (nc, nr) == exit_cell:
                    self.next_level()
        self.complete_action()
