"""Generate scripts/pod_lean_driver.py: the stock Duck runner with the 'lean'
harness wrappers applied in-process, for a RunPod measurement run.

Why a generated file: the pod clones only the UPSTREAM bundle (no atlas repo),
so the hint text and the runtime wrappers must travel inside one small python
file. They are taken verbatim from scripts/build_stocklab_notebook.py with
ATLAS_STOCKLAB_HINT=lean -- the same strings the Kaggle battle notebook ships.

usage:
    python scripts/build_pod_lean_driver.py        # writes scripts/pod_lean_driver.py
"""
from __future__ import annotations

import importlib.util
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HINT = os.environ.get("ATLAS_STOCKLAB_HINT", "lean").strip().lower() or "lean"   # lean | leanshort
os.environ["ATLAS_STOCKLAB_HINT"] = HINT
spec = importlib.util.spec_from_file_location("bsn", ROOT / "scripts" / "build_stocklab_notebook.py")
bsn = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bsn)  # type: ignore[union-attr]
hint = bsn.hint_text()
runtime = bsn.runtime_text()
assert "EVENT PROTOCOL" in hint and "_ln_prompt" in runtime and "_LN_HELPERS" in runtime
assert HINT != "leanshort" or "_ls_system" in runtime

DRIVER = f'''"""Stock Duck runner + the 'lean' harness wrappers (generated by
scripts/build_pod_lean_driver.py -- do not edit by hand).

Runs inference.framework.run.main() with the given argv after patching
inference.agent.tool_agent exactly like the Kaggle battle notebook cell does:
  1. append the lean hint to PYTHON_ADDENDUM (system prompt addendum);
  2. exec the runtime wrappers (compact prompt + [STATE]/[DIFF]/[HUD]/[NOTICE]/
     [SHORT], sandbox helpers, event PROTOCOL, thinking only on event turns).
Use with --deployment-target inline so the patched module serves every game
thread of this process.
"""
import sys

LEAN_HINT = {hint!r}
LEAN_RUNTIME = {runtime!r}


def apply_lean() -> None:
    import inference.agent.tool_agent as agent
    before = len(agent.PYTHON_ADDENDUM)
    agent.PYTHON_ADDENDUM = agent.PYTHON_ADDENDUM + LEAN_HINT
    print(f"pod-lean: hint applied -- addendum {{before}} -> {{len(agent.PYTHON_ADDENDUM)}} chars", flush=True)
    exec(LEAN_RUNTIME, {{"__name__": "pod_lean_runtime"}})
    assert agent.ToolAgent._build_user_prompt.__name__ == "_ln_prompt"
    assert agent.ToolAgent._run_python_tool.__name__ == "_ln_run"
    assert agent.run_sandboxed_python.__name__ == "_ln_sandbox"
    assert agent.build_chat_payload.__name__ == "_ln_payload"
    if "_ls_system" in LEAN_RUNTIME:
        assert agent._build_system_prompt.__name__ == "_ls_system"
    print("pod-lean: wrappers verified on inference.agent.tool_agent (variant {HINT})", flush=True)


def main() -> int:
    apply_lean()
    from inference.framework.run import main as run_main
    return run_main()


if __name__ == "__main__":
    sys.exit(main() or 0)
'''

out = ROOT / "scripts" / ("pod_lean_driver.py" if HINT == "lean" else f"pod_{HINT}_driver.py")
out.write_text(DRIVER, encoding="utf-8")
print(f"written {out} ({len(DRIVER)} chars; hint {len(hint)}, runtime {len(runtime)})")
