"""Generate the long-level testbed games (batch of 01.09.2026).

Why. The eleven public games we never clear need a median of 54 human actions
on level 1 (range 21-78); the seven we always clear need 22. Our own testbed
topped out at 20, so it could not reproduce the failure that costs us the
most. lm01 was written by hand as the PURE LENGTH control -- long, but with no
rule to discover. These five add a discovery burden on top of the same
locomotion, so the batch separates "long" from "long AND hidden".

Design contract, the same for all five:

  * locomotion is identical everywhere (ACTION1-4 move one cell) so the games
    differ in what must be LEARNED, not in how you walk;
  * every game exposes a PURE mirror of its own rules -- sim_initial /
    sim_step / sim_done -- and the class plays through that mirror. The guard
    then finds the true optimum by BFS over the same functions, so a baked
    baseline can never be a hand-count. lm01 shipped a hand-counted 53 that
    BFS corrected to 65; nothing here is trusted to arithmetic;
  * level 1 lands in 50-80 actions, verified by that BFS, not asserted here.

usage:
    python scripts/gen_long_games.py          # write the five game dirs
    python scripts/gen_long_games.py --check  # report the optimum per level
"""

from __future__ import annotations

import argparse
import json
from collections import deque
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OWN = ROOT / "our_games"

GRID = 16
CELL = 4

# --- the shared skeleton ---------------------------------------------------
# Everything above the mechanic hook is identical across the five games.

HEADER = '''# Original game for the atlas testbed (01.09.2026) -- NOT an ARC Prize game.
# GENERATED by scripts/gen_long_games.py -- edit the generator, not this file.
#
# "{title}" ({gid}) -- long-level batch.
#
# {blurb}
#
# Level 1 optimum is found by BFS over sim_step/sim_done in
# scripts/test_atlas_long_games.py and baked into metadata.json. Never
# hand-count a baseline: lm01 shipped 53 that way and the real answer was 65.

from arcengine import (
    ARCBaseGame,
    BlockingMode,
    Camera,
    GameAction,
    Level,
    Sprite,
)

CELL = {cell}
GRID = {grid}

WALL = 9
PLAYER = 1
EXIT = 3
MARK = 4
MARK_DONE = 8
HAZARD = 2

LEVELS = {levels}


def _rect(color):
    return [[color] * CELL for _ in range(CELL)]


def _box_px(color):
    return [[color if i in (0, CELL - 1) or j in (0, CELL - 1) else 0
             for j in range(CELL)] for i in range(CELL)]


def _solid_px(color):
    return [[color if 0 < i < CELL - 1 and 0 < j < CELL - 1 else 0
             for j in range(CELL)] for i in range(CELL)]


def walkable(spec):
    """Every cell inside the border that is not a wall."""
    walls = {{tuple(w) for w in spec["walls"]}}
    return {{(c, r) for c in range(1, GRID - 1) for r in range(1, GRID - 1)
            if (c, r) not in walls}}


MOVES = {{1: (0, -1), 2: (0, 1), 3: (-1, 0), 4: (1, 0)}}
'''

# --- per-game mechanics ----------------------------------------------------
# Each entry supplies: the pure simulation, the sprite build, and the level
# specs. `sim_step(spec, state, action) -> state` and `sim_done(spec, state)`
# are what both the class and the guard's BFS run on.

MECHANICS: dict[str, dict] = {}

MECHANICS["gk01"] = dict(
    title="Gatekeeper",
    blurb=("Three pads must be PRESSED (ACTION5), not merely stepped on, and the "
           "exit stays inert until all three are down. The discovery is that "
           "standing somewhere is not the same as acting there -- an agent that "
           "only walks will cross every pad and never open the exit."),
    actions="[1, 2, 3, 4, 5]",
    sim='''

def sim_initial(spec):
    return (tuple(spec["start"]), frozenset())


def sim_step(spec, state, action):
    pos, pressed = state
    if action == 5:
        if pos in {tuple(p) for p in spec["pads"]} and pos not in pressed:
            return (pos, pressed | {pos})
        return state
    delta = MOVES.get(action)
    if delta is None:
        return state
    nxt = (pos[0] + delta[0], pos[1] + delta[1])
    return (nxt, pressed) if nxt in walkable(spec) else state


def sim_done(spec, state):
    pos, pressed = state
    return len(pressed) == len(spec["pads"]) and pos == tuple(spec["exit"])
''',
    sprites='''
    for i, (c, r) in enumerate(spec["pads"]):
        sprites.append(Sprite(_box_px(MARK), name=f"pad_{i}", x=c * CELL, y=r * CELL,
                              layer=1, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
''',
    sync='''
        for i, (c, r) in enumerate(spec["pads"]):
            s = self._sprite(f"pad_{i}")
            if s is not None:
                px = _box_px(MARK_DONE if (c, r) in self._atlas_state[1] else MARK)
                for rr in range(CELL):
                    for cc in range(CELL):
                        s.pixels[rr][cc] = px[rr][cc]
''',
)

MECHANICS["ac01"] = dict(
    title="Accumulator",
    blurb=("Eight tokens are scattered; the exit does nothing until every one is "
           "collected. Stepping on a token takes it. The discovery is that the "
           "goal is CONDITIONAL -- reaching the exit early looks like a failure "
           "of navigation when it is really a failure of counting."),
    actions="[1, 2, 3, 4]",
    sim='''

def sim_initial(spec):
    return (tuple(spec["start"]), frozenset(tuple(t) for t in spec["tokens"]))


def sim_step(spec, state, action):
    pos, left = state
    delta = MOVES.get(action)
    if delta is None:
        return state
    nxt = (pos[0] + delta[0], pos[1] + delta[1])
    if nxt not in walkable(spec):
        return state
    return (nxt, left - {nxt}) if nxt in left else (nxt, left)


def sim_done(spec, state):
    pos, left = state
    return not left and pos == tuple(spec["exit"])
''',
    sprites='''
    for i, (c, r) in enumerate(spec["tokens"]):
        sprites.append(Sprite(_solid_px(MARK), name=f"token_{i}", x=c * CELL, y=r * CELL,
                              layer=1, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
''',
    sync='''
        for i, (c, r) in enumerate(spec["tokens"]):
            s = self._sprite(f"token_{i}")
            if s is not None:
                gone = (c, r) not in self._atlas_state[1]
                px = [[0] * CELL for _ in range(CELL)] if gone else _solid_px(MARK)
                for rr in range(CELL):
                    for cc in range(CELL):
                        s.pixels[rr][cc] = px[rr][cc]
''',
)

MECHANICS["ky01"] = dict(
    title="Keyring",
    blurb=("Keys open doors, but only in the order the doors appear along the "
           "route -- taking a later key first wastes the trip. The discovery is "
           "ORDER: the board shows what to collect and says nothing about when, "
           "and a wrong order is recoverable but expensive."),
    actions="[1, 2, 3, 4]",
    sim='''

def sim_initial(spec):
    return (tuple(spec["start"]), 0)


def sim_step(spec, state, action):
    pos, opened = state
    delta = MOVES.get(action)
    if delta is None:
        return state
    nxt = (pos[0] + delta[0], pos[1] + delta[1])
    if nxt not in walkable(spec):
        return state
    doors = [tuple(d) for d in spec["doors"]]
    if nxt in doors:
        idx = doors.index(nxt)
        if idx != opened:
            return state           # a shut door blocks
        return (nxt, opened + 1)
    return (nxt, opened)


def sim_done(spec, state):
    pos, opened = state
    return opened == len(spec["doors"]) and pos == tuple(spec["exit"])
''',
    sprites='''
    for i, (c, r) in enumerate(spec["doors"]):
        sprites.append(Sprite(_box_px(MARK), name=f"door_{i}", x=c * CELL, y=r * CELL,
                              layer=1, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
''',
    sync='''
        for i, (c, r) in enumerate(spec["doors"]):
            s = self._sprite(f"door_{i}")
            if s is not None:
                px = _box_px(MARK_DONE if i < self._atlas_state[1] else MARK)
                for rr in range(CELL):
                    for cc in range(CELL):
                        s.pixels[rr][cc] = px[rr][cc]
''',
)

MECHANICS["fr01"] = dict(
    title="Ferry",
    blurb=("Crates must be carried to the depot ONE AT A TIME. Stepping on a "
           "crate picks it up; stepping on the depot while loaded drops it. The "
           "discovery is CAPACITY: the board shows several crates and one depot "
           "and says nothing about how many hands you have, so the obvious plan "
           "-- sweep them all up, then deliver -- silently does nothing."),
    actions="[1, 2, 3, 4]",
    sim='''

def sim_initial(spec):
    return (tuple(spec["start"]), False, frozenset(tuple(c) for c in spec["crates"]), 0)


def sim_step(spec, state, action):
    pos, loaded, crates, done = state
    delta = MOVES.get(action)
    if delta is None:
        return state
    nxt = (pos[0] + delta[0], pos[1] + delta[1])
    if nxt not in walkable(spec):
        return state
    if not loaded and nxt in crates:
        return (nxt, True, crates - {nxt}, done)
    if loaded and nxt == tuple(spec["depot"]):
        return (nxt, False, crates, done + 1)
    return (nxt, loaded, crates, done)


def sim_done(spec, state):
    pos, loaded, crates, done = state
    return not crates and not loaded and pos == tuple(spec["exit"])
''',
    sprites='''
    dc, dr = spec["depot"]
    sprites.append(Sprite(_box_px(MARK_DONE), name="depot", x=dc * CELL, y=dr * CELL,
                          layer=1, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    for i, (c, r) in enumerate(spec["crates"]):
        sprites.append(Sprite(_solid_px(MARK), name=f"crate_{i}", x=c * CELL, y=r * CELL,
                              layer=2, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
''',
    sync='''
        for i, (c, r) in enumerate(spec["crates"]):
            s = self._sprite(f"crate_{i}")
            if s is not None:
                gone = (c, r) not in self._atlas_state[2]
                px = [[0] * CELL for _ in range(CELL)] if gone else _solid_px(MARK)
                for rr in range(CELL):
                    for cc in range(CELL):
                        s.pixels[rr][cc] = px[rr][cc]
''',
)

MECHANICS["rl01"] = dict(
    title="Relay",
    blurb=("Two gates, and a switch that opens one while closing the other. The "
           "switch is nowhere near either gate. The discovery is NON-LOCAL "
           "CAUSALITY: acting here changes the board there, which is invisible "
           "from the spot where you act -- the class of rule an agent cannot "
           "deduce without walking back to look."),
    actions="[1, 2, 3, 4]",
    sim='''

def sim_initial(spec):
    return (tuple(spec["start"]), 0, 0)


def sim_step(spec, state, action):
    pos, phase, opened = state
    delta = MOVES.get(action)
    if delta is None:
        return state
    nxt = (pos[0] + delta[0], pos[1] + delta[1])
    if nxt not in walkable(spec):
        return state
    gates = [tuple(g) for g in spec["gates"]]
    if nxt in gates:
        idx = gates.index(nxt)
        # a gate opens only in ITS phase and only in turn: gate i wants phase
        # i % 2, so passing three of them forces two trips back to the switch
        if idx != opened or (idx % 2) != phase:
            return state
        return (nxt, phase, opened + 1)
    if nxt == tuple(spec["switch"]):
        return (nxt, 1 - phase, opened)
    return (nxt, phase, opened)


def sim_done(spec, state):
    return state[2] == len(spec["gates"]) and state[0] == tuple(spec["exit"])
''',
    sprites='''
    sc, sr = spec["switch"]
    sprites.append(Sprite(_solid_px(MARK_DONE), name="switch", x=sc * CELL, y=sr * CELL,
                          layer=1, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    for i, (c, r) in enumerate(spec["gates"]):
        sprites.append(Sprite(_box_px(MARK), name=f"gate_{i}", x=c * CELL, y=r * CELL,
                              layer=2, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
''',
    sync='''
        for i, (c, r) in enumerate(spec["gates"]):
            s = self._sprite(f"gate_{i}")
            if s is not None:
                px = _box_px(MARK if i == self._atlas_state[1] else HAZARD)
                for rr in range(CELL):
                    for cc in range(CELL):
                        s.pixels[rr][cc] = px[rr][cc]
''',
)

MECHANICS["cy01"] = dict(
    title="Cycle",
    blurb=("A hazard sweeps one corridor on a fixed period; entering it on the "
           "wrong beat sends you back to the start of the level. ACTION5 waits. "
           "The discovery is that DOING NOTHING is a move -- an agent whose "
           "machinery punishes turns without progress can never learn to wait."),
    actions="[1, 2, 3, 4, 5]",
    sim='''

def hazard_at(spec, t):
    """Cells the sweeper occupies at time t."""
    lane = [tuple(c) for c in spec["lane"]]
    period = 2 * (len(lane) - 1)
    i = t % period
    if i >= len(lane):
        i = period - i
    return {lane[i]}


def sim_initial(spec):
    return (tuple(spec["start"]), 0)


def sim_step(spec, state, action):
    pos, t = state
    nt = t + 1
    if action == 5:
        return (pos, nt)
    delta = MOVES.get(action)
    if delta is None:
        return (pos, nt)
    nxt = (pos[0] + delta[0], pos[1] + delta[1])
    if nxt not in walkable(spec):
        return (pos, nt)
    if nxt in hazard_at(spec, nt):
        return (tuple(spec["start"]), nt)
    return (nxt, nt)


def sim_done(spec, state):
    return state[0] == tuple(spec["exit"])
''',
    sprites='''
    for i, (c, r) in enumerate(spec["lane"]):
        sprites.append(Sprite(_box_px(HAZARD), name=f"lane_{i}", x=c * CELL, y=r * CELL,
                              layer=1, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    sprites.append(Sprite(_solid_px(HAZARD), name="sweeper",
                          x=spec["lane"][0][0] * CELL, y=spec["lane"][0][1] * CELL,
                          layer=3, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
''',
    sync='''
        cell = sorted(hazard_at(spec, self._atlas_state[1]))[0]
        s = self._sprite("sweeper")
        if s is not None:
            s.set_position(cell[0] * CELL, cell[1] * CELL)
''',
)

MECHANICS["tw01"] = dict(
    title="Twin",
    blurb=("Two avatars move at once: one mirrors the other left-right. Both "
           "must stand on their own target at the same time. The discovery is "
           "COUPLING -- every action helps one and hurts the other, so the "
           "board cannot be read as a single-agent maze at all."),
    actions="[1, 2, 3, 4]",
    sim='''

def sim_initial(spec):
    return (tuple(spec["start"]), tuple(spec["start_b"]))


def sim_step(spec, state, action):
    a, b = state
    delta = MOVES.get(action)
    if delta is None:
        return state
    cells = walkable(spec)
    na = (a[0] + delta[0], a[1] + delta[1])
    nb = (b[0] - delta[0], b[1] + delta[1])
    if na not in cells:
        na = a
    if nb not in cells:
        nb = b
    return (na, nb)


def sim_done(spec, state):
    return state[0] == tuple(spec["exit"]) and state[1] == tuple(spec["exit_b"])
''',
    sprites='''
    ec, er = spec["exit_b"]
    sprites.append(Sprite(_box_px(MARK), name="exit_b", x=ec * CELL, y=er * CELL,
                          layer=1, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    sc, sr = spec["start_b"]
    sprites.append(Sprite(_solid_px(MARK), name="twin", x=sc * CELL, y=sr * CELL,
                          layer=2, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
''',
    sync='''
        twin = self._sprite("twin")
        if twin is not None:
            twin.set_position(self._atlas_state[1][0] * CELL, self._atlas_state[1][1] * CELL)
''',
)

BODY = '''

def _build_level(index, spec):
    sprites = []
    walls = {{tuple(w) for w in spec["walls"]}}
    for r in range(GRID):
        for c in range(GRID):
            if r in (0, GRID - 1) or c in (0, GRID - 1) or (c, r) in walls:
                sprites.append(Sprite(_rect(WALL), name=f"wall_{{r}}_{{c}}",
                                      x=c * CELL, y=r * CELL,
                                      blocking=BlockingMode.PIXEL_PERFECT,
                                      tags=["sys_static"]))
    ec, er = spec["exit"]
    sprites.append(Sprite(_box_px(EXIT), name="exit", x=ec * CELL, y=er * CELL,
                          layer=1, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
{sprites}
    sc, sr = spec["start"]
    sprites.append(Sprite(_solid_px(PLAYER), name="player", x=sc * CELL, y=sr * CELL,
                          layer=4, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    return Level(sprites=sprites, grid_size=(GRID * CELL, GRID * CELL),
                 name=f"level_{{index + 1}}")


class {cls}(ARCBaseGame):
    def __init__(self, seed: int = 0, debug: bool = False):
        levels = [_build_level(i, spec) for i, spec in enumerate(LEVELS)]
        super().__init__(
            game_id="{gid}",
            levels=levels,
            camera=Camera(width=GRID * CELL, height=GRID * CELL),
            debug=debug,
            available_actions={actions},
            seed=seed,
        )
        self._atlas_state = None
        self._load()

    def _load(self):
        self._atlas_state = sim_initial(LEVELS[self.level_index])

    def on_set_level(self, level):
        self._load()

    def level_reset(self):
        super().level_reset()
        self._load()

    def full_reset(self):
        super().full_reset()
        self._load()

    def _sprite(self, name):
        found = self.current_level.get_sprites_by_name(name)
        return found[0] if found else None

    def _sync(self):
        spec = LEVELS[self.level_index]
        player = self._sprite("player")
        if player is not None:
            pos = self._atlas_state[0]
            player.set_position(pos[0] * CELL, pos[1] * CELL)
{sync}

    def step(self) -> None:
        spec = LEVELS[self.level_index]
        action = self.action.id
        if action == GameAction.RESET:
            self._sync()
            self.complete_action()
            return
        ids = {{
            GameAction.ACTION1: 1, GameAction.ACTION2: 2,
            GameAction.ACTION3: 3, GameAction.ACTION4: 4,
            GameAction.ACTION5: 5,
        }}
        if action in ids:
            self._atlas_state = sim_step(spec, self._atlas_state, ids[action])
        self._sync()
        if sim_done(spec, self._atlas_state):
            self.next_level()
        self.complete_action()
'''


# --- level layouts ---------------------------------------------------------
# A ring corridor around a solid core: walking the ring is long, and the
# mechanics decide how many times you must go round.

def ring_walls(inner: int = 3) -> list[tuple[int, int]]:
    """A solid block in the middle, so the only route is the outer ring."""
    lo, hi = inner, GRID - 1 - inner
    return [(c, r) for c in range(lo, hi + 1) for r in range(lo, hi + 1)]


def perimeter(walls) -> list[tuple[int, int]]:
    """Ring cells in walking order, starting at (1,1) going clockwise.

    Placing marks by PERIMETER INDEX instead of by hand-picked coordinates is
    what makes the layouts survive a geometry change. The first attempt used
    literal (col,row) pairs; widening the ring by one cell put half of them
    inside the wall block and every level became unsolvable at once.
    """
    blocked = {tuple(w) for w in walls}
    lo, hi = 1, GRID - 2
    ring = []
    for c in range(lo, hi + 1):
        ring.append((c, lo))
    for r in range(lo + 1, hi + 1):
        ring.append((hi, r))
    for c in range(hi - 1, lo - 1, -1):
        ring.append((c, hi))
    for r in range(hi - 1, lo, -1):
        ring.append((lo, r))
    return [cell for cell in ring if cell not in blocked]


def spread(ring, count, offset=0):
    """`count` cells spaced evenly around the ring, skipping the start cell."""
    step = len(ring) / (count + 1)
    return [ring[int((i + 1) * step + offset) % len(ring)] for i in range(count)]


# rl01 gate/switch placements, by perimeter index, produced by the search
# described in specs_for. Regenerate with the snippet in that comment if the
# ring geometry ever changes -- these indices are meaningless on another ring.
RL01_LAYOUTS = [
    (26, 9, 5, 11),    # optimum 55
    (33, 5, 48, 8),    # optimum 62
    (20, 21, 10, 7),   # optimum 66
    (29, 6, 42, 10),   # optimum 70
    (29, 32, 4, 18),   # optimum 78
]


def specs_for(gid: str) -> list[dict]:
    """Nine levels per game, with the load rising level by level.

    01.09, measured against the public 25: they carry a median of 7 levels
    (range 6-10) and their baseline grows x3.2 from level 1 to level 5 -- the
    first level is a warm-up before the real game. Our first batch shipped 5
    flat levels (growth x0.9), which left two gaps that matter:

      * RHAE divides by the sum of level weights, so a 5-level game and a
        10-level game with one level cleared score 6.7 and 1.8. A flat
        5-level testbed cannot produce comparable RHAE at all;
      * a flat game never tests whether an agent that cleared level 1 can
        keep going when the next level is twice as long.

    So the count rises to 9 and the load per level rises with it. Level 1
    still has to land in 50-80: that is the class we actually fail on, and
    losing it to make room for escalation would defeat the batch.
    """
    walls = ring_walls()
    ring = perimeter(walls)
    n = len(ring)
    out = []
    for lvl in range(9):
        base = dict(walls=walls, start=ring[0])
        off = lvl * 3
        # grow: level 1 carries `lo` marks, level 9 carries `hi`
        def grow(lo, hi):
            return lo + round((hi - lo) * lvl / 8)
        # Escalate where the MECHANIC allows it, and say so where it does not.
        # Three of the five are "visit each once", and one lap of a fixed ring
        # covers any number of marks: adding pads moved gk01 from 55 to 58
        # across nine levels. Growing the ring instead (32x32, arc-based
        # placement) does escalate -- and blows the BFS check past ten minutes,
        # because the state space is cells x 2^marks. An unverified baseline is
        # exactly what this batch exists to avoid, so the ring stays at 16 and
        # only the two mechanics whose cost is MULTIPLICATIVE escalate:
        # fr01 (one trip per crate) and rl01 (one return per gate).
        off = lvl * 3

        def grow(lo, hi):
            return lo + round((hi - lo) * lvl / 8)

        if gid == "gk01":
            base.update(pads=spread(ring, 3 + (lvl % 3), off),
                        exit=ring[(n // 2 + off) % n])
        elif gid == "ac01":
            base.update(tokens=spread(ring, 8, off), exit=ring[(n // 2 + off) % n])
        elif gid == "ky01":
            base.update(doors=spread(ring, 3, off % 5),
                        exit=ring[(n - 2 - (off % 5)) % n])
        elif gid == "fr01":
            base.update(crates=spread(ring, grow(2, 5), off + n // 4),
                        depot=ring[2], exit=ring[(n // 2 + off) % n])
        elif gid == "rl01":
            g0, g1, g2, sw = RL01_LAYOUTS[lvl % len(RL01_LAYOUTS)]
            gates = [ring[g0], ring[g1], ring[g2]]
            for extra in range(grow(0, 2)):
                gates.append(ring[(g0 + 7 * (extra + 1)) % n])
            base.update(gates=gates, switch=ring[sw], exit=ring[(g2 + 2) % n])
        out.append(base)
    return out


# --- BFS over the generated simulation -------------------------------------

def optimum(module, spec, limit: int = 400_000) -> int | None:
    """Shortest action count that satisfies sim_done -- the true baseline."""
    start = module.sim_initial(spec)
    if module.sim_done(spec, start):
        return 0
    seen = {start}
    queue = deque([(start, 0)])
    actions = [1, 2, 3, 4, 5]
    while queue and len(seen) < limit:
        state, dist = queue.popleft()
        for act in actions:
            nxt = module.sim_step(spec, state, act)
            if nxt in seen:
                continue
            if module.sim_done(spec, nxt):
                return dist + 1
            seen.add(nxt)
            queue.append((nxt, dist + 1))
    return None


HASHES = {"gk01": "b2c3d4e5", "ac01": "c3d4e5f6", "ky01": "d4e5f6a7",
          "fr01": "a7b8c9d0", "rl01": "b8c9d0e1",
          "cy01": "e5f6a7b8", "tw01": "f6a7b8c9"}


def render(gid: str) -> str:
    mech = MECHANICS[gid]
    levels = json.dumps(specs_for(gid), indent=4).replace("[\n", "[\n").replace("null", "None")
    head = HEADER.format(title=mech["title"], gid=gid, blurb=mech["blurb"],
                         cell=CELL, grid=GRID, levels=levels)
    body = BODY.format(cls=gid.capitalize(), gid=gid, actions=mech["actions"],
                       sprites=mech["sprites"].rstrip("\n"), sync=mech["sync"].rstrip("\n"))
    return head + mech["sim"] + body


def load(gid: str, source: str):
    import types
    module = types.ModuleType(f"gen_{gid}")
    stub = types.ModuleType("arcengine")
    for name in ("ARCBaseGame", "BlockingMode", "Camera", "GameAction", "Level", "Sprite"):
        setattr(stub, name, type(name, (), {"__init__": lambda self, *a, **k: None}))
    import sys
    saved = sys.modules.get("arcengine")
    sys.modules["arcengine"] = stub
    try:
        exec(compile(source, f"<{gid}>", "exec"), module.__dict__)
    finally:
        if saved is None:
            sys.modules.pop("arcengine", None)
        else:
            sys.modules["arcengine"] = saved
    return module


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="only report the optimum per level, write nothing")
    args = ap.parse_args()

    # cy01 (timing) and tw01 (coupled avatars) are NOT in this list on
    # purpose. Both need a geometry the ring cannot give: the sweeper's lane
    # has to sit on a forced chokepoint, and the mirrored twin collapses to a
    # single-agent walk whenever the walls are symmetric. Three rounds of
    # parameter tweaking moved their optimum between 3 and 26 actions and
    # never into the 50-80 band -- that is a design problem, not a tuning one.
    # Shipping them at 8 actions would quietly put two SHORT games into a
    # batch whose entire purpose is long levels.
    for gid in ("gk01", "ac01", "ky01", "fr01", "rl01"):
        source = render(gid)
        module = load(gid, source)
        opt = [optimum(module, spec) for spec in module.LEVELS]
        flag = "" if opt[0] is not None and 50 <= opt[0] <= 80 else "   <-- ВНЕ ДИАПАЗОНА 50-80"
        print(f"{gid}  {MECHANICS[gid]['title']:14} оптимум по уровням: {opt}{flag}")
        if args.check:
            continue
        if any(o is None for o in opt):
            print(f"  {gid}: не пишу -- есть нерешаемый уровень")
            continue
        out = OWN / gid / HASHES[gid]
        out.mkdir(parents=True, exist_ok=True)
        (out / f"{gid}.py").write_text(source, encoding="utf-8")
        (out / "metadata.json").write_text(json.dumps({
            "game_id": f"{gid}-{HASHES[gid]}",
            "title": f"{MECHANICS[gid]['title']} (atlas testbed, long-level batch)",
            "default_fps": 6,
            "tags": ["keyboard", "atlas_own", "atlas_long"],
            "class_name": gid.capitalize(),
            "baseline_actions": opt,
        }, indent=2) + "\n", encoding="utf-8")
        print(f"  записано: {out}")


if __name__ == "__main__":
    main()
