"""Cross-round per-game summary of the vision-teacher era (all dirs matching
data/teacher/*_vision_*): best level per game over every episode, each
episode's best@turns, and the pure-text Gemini-Pro ceiling for comparison.

Usage:
    .venv/Scripts/python.exe scripts/summarize_all_rounds.py [--md docs/vision_teacher_stats.md]
"""
from __future__ import annotations

import argparse
import collections
import glob
import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--md", default=None)
    p.add_argument("--glob", default="data/teacher/*_vision_2026*")
    args = p.parse_args()

    rows: dict[str, list[tuple[str, int, int, int]]] = collections.defaultdict(list)
    for d in sorted(glob.glob(str(ROOT / args.glob))):
        m = re.search(r"_(round\w+?)_vision", os.path.basename(d))
        rnd = m.group(1) if m else "r1pro"
        for f in glob.glob(os.path.join(d, "*-r0.jsonl")):
            recs = [json.loads(l) for l in open(f, encoding="utf-8") if l.strip()]
            turns = [r for r in recs if r.get("turn", 0) > 0 and "turn_failed" not in r]
            best = max((r.get("level") or 0 for r in turns), default=0)
            acts = sum(r.get("actions_executed") or 0 for r in turns)
            game = os.path.basename(f).split("-")[0]
            rows[game].append((rnd, best, len(turns), acts))

    ceil: dict[str, tuple[int, int]] = {}
    stats = ROOT / "docs" / "gemini_pro_stats.md"
    if stats.exists():
        for line in stats.read_text(encoding="utf-8").splitlines():
            m = re.match(r"\|\s*([a-z0-9]{4})\s*\|\s*(\d+)\s*\|\s*(\d+)", line)
            if m:
                ceil[m.group(1)] = (int(m.group(2)), int(m.group(3)))

    lines = ["| game | Pro text / +hint | vision best | episodes: round:best@turns |",
             "|---|---|---|---|"]
    tot = above = eq = wins = 0
    for g in sorted(rows):
        best = max(b for _, b, _, _ in rows[g])
        tot += best
        pc = ceil.get(g, (0, 0))
        above += best > pc[0]
        eq += best == pc[0]
        eps = ", ".join(f"{r}:{b}@{t}" for r, b, t, _ in rows[g])
        lines.append(f"| {g} | {pc[0]} / {pc[1]} | **{best}** | {eps} |")
    n_eps = sum(len(v) for v in rows.values())
    summary = (f"games {len(rows)}, episodes {n_eps}, sum of best levels {tot}, "
               f"above pure-text Pro ceiling: {above}, equal: {eq}, below: {len(rows) - above - eq}")
    table = "\n".join(lines)
    print(table)
    print()
    print(summary)
    if args.md:
        Path(args.md).write_text(
            "# Vision-teacher era (21.08.2026): best level per game across rounds\n\n"
            "Generated by `scripts/summarize_all_rounds.py`. r1pro = Gemini 3.1 Pro + vision "
            "(round 1, stopped early); round2flash..round4B3 = gemini-3.7-flash + vision. "
            "`Pro text / +hint` = text-only Gemini Pro ceiling from docs/gemini_pro_stats.md.\n\n"
            + table + "\n\n" + summary + "\n", encoding="utf-8")
        print("written", args.md)


if __name__ == "__main__":
    main()
