# Original game for the atlas testbed (30.08.2026) -- NOT an ARC Prize game.
# "Clockgates" (cl01) -- rank-12 mechanic from the Gemini round-11 pool
# plan: temporal arithmetic -- passing through gates requires being in
# phase with their period.
#
# Rules: ACTION1-4 move, ACTION5 waits in place. Each gate has a period k
# (2 or 3) and is OPEN only on the action where the running action count
# hits a multiple of k. The gate's pixels cycle through its phase colors
# every action, so the rule is fully visible in the frame (no hidden
# randomness). Reach the exit pad; waiting for the beat is part of the
# optimal plan.

from arcengine import (
    ARCBaseGame,
    BlockingMode,
    Camera,
    GameAction,
    Level,
    Sprite,
)

CELL = 3
GRID = 21


# --- pixel helpers, added 03.09 by scripts/cellify_sprites.py ---------------
# These replace literal pixel indices so the sprite renders at any CELL. The
# shapes are exactly what the literals drew at CELL == 4, which
# scripts/frame_fingerprint.py verifies by hashing every frame before and
# after the rewrite.

def _fill_inner(px, color):
    """Everything except the one-pixel border."""
    for _r in range(1, CELL - 1):
        for _c in range(1, CELL - 1):
            px[_r][_c] = color
    return px


def _fill_edge(px, side, color):
    """The middle stretch of one edge -- the part that is not a corner."""
    span = range(1, CELL - 1) if CELL > 2 else range(CELL)
    for _i in span:
        if side == "top":
            px[0][_i] = color
        elif side == "bottom":
            px[CELL - 1][_i] = color
        elif side == "left":
            px[_i][0] = color
        else:
            px[_i][CELL - 1] = color
    return px


def _fill_row(px, col, color):
    """The middle rows of one column."""
    for _r in range(1, CELL - 1):
        px[_r][col] = color
    return px

WALL = 9
AGENT = 3
EXIT = 4
GATE_OPEN = 3
PHASE_COLORS = [8, 6, 11]

# rows: '#'=wall, 'P'=agent, 'E'=exit, '2'/'3'=gate with that period.
LEVELS = [
    # 03.09: regenerated by scripts/regen_short_levels.py on a full
    # 64x64 board (GRID 8 -> 16), nine levels along the public
    # difficulty curve. The old five levels cost 6-10 actions where the
    # public median level 1 is 30, so clearing them said nothing about
    # the games we are actually scored on -- and one of them (gv01)
    # shipped a level whose true optimum was a single action.
    # Every level below was PROVEN by BFS through the engine, never
    # counted by hand, and carries the objects of the level it replaces
    # in the same numbers.
    dict(rows=[
        '#####################',
        '#.#.........#.......#',
        '#.###.###.###.#####.#',
        '#...#...#.3E......#.#',
        '###.#####.#########.#',
        '#.#.#...#.#.........#',
        '#.#.#.#.#.#.#######.#',
        '#.#...#.#.#.#...#...#',
        '#.#####.###.#.#.#.###',
        '#...#...#...#.#.#.#.#',
        '#.#.#.###.###.###.#.#',
        '#.#.#.#..P#.....#.#.#',
        '#.###.#.###.###.#.#.#',
        '#.....#.#.#.#.#...#.#',
        '#.#####.#.#.#.#####.#',
        '#.....#.#...#...#...#',
        '#####.#.#.###.#.#.#.#',
        '#...#...#.#...#...#.#',
        '#.#######.#########.#',
        '#...................#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#...#.....#.........#',
        '###.#####.#E#######.#',
        '#.#.....#.#.#.....#.#',
        '#.#####.#.#.#.#####.#',
        '#...#...#.....#...#.#',
        '###.#.#######.#.#.#.#',
        '#...#.......#.#.#...#',
        '#.#.#######.###.#####',
        '#.#.......#...#.#...#',
        '#.###########.#.#.#.#',
        '#...#.......#.#3#3#.#',
        '#.#.#.#####.#.#.#.#.#',
        '#.#...#...#...#...#.#',
        '#.#####.#########.#.#',
        '#...#.......#...#.#.#',
        '###.#.###.#.#.#.###.#',
        '#.#.#...#.#...#.....#',
        '#.#.#####.#########.#',
        '#.........#.P.......#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#.#2..#.....#.......#',
        '#.#.#.#.#.#.###.###.#',
        '#.#.#...#.#...#...#.#',
        '#.#####.#.###.###.###',
        '#....E#.#...#...#...#',
        '#####.#.###.###.###.#',
        '#.#...#.#...#.....#.#',
        '#.#.#####.#######.#.#',
        '#...#...#.......#.#.#',
        '#.###.#.###.###.#.#.#',
        '#.#2..#...#.#...#...#',
        '#.#.#####.#.#.#######',
        '#...#.P.#.#.#.#.....#',
        '#####.###.###.#.###.#',
        '#...#...#...#.#...#.#',
        '#.#.#.#.###.#.#.###.#',
        '#.#...#.#...#...#...#',
        '#.#####.#.#######.#.#',
        '#.....#...........#.#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#.....#.....#.......#',
        '#####.###.#.#####.#.#',
        '#...#.....#.....#.#.#',
        '#.#.###########.#.#.#',
        '#.#.....#.....#...#.#',
        '#.#####.#.###.#####.#',
        '#...#...#.#.....#...#',
        '#.#.#####.#.###.#.###',
        '#.#...#...#...#.#..E#',
        '#.###.#.#####.#####.#',
        '#.#.#...#...#...#...#',
        '#.#.#####.#.###.#.###',
        '#...#.....#.#.#...#.#',
        '###.#.#.###.#.#####.#',
        '#.#.#.#.#.#...#.3...#',
        '#.#.#.#.#.###.#####.#',
        '#.P.#.#.#..2#.#...#.#',
        '#.#####.#.###.#.#.#.#',
        '#2......#.......#...#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#.......#...........#',
        '#######P#.#####.#####',
        '#...#...#.#.3.#.#...#',
        '#.###.###.###3#.#.#.#',
        '#.#...#.......#...#.#',
        '#.#.###.#########.#.#',
        '#.#.#...#.......#.#.#',
        '#.#.###.#.#####.#.#E#',
        '#.#...#.#...#...#.#.#',
        '#.###.###.#.#.###.#.#',
        '#...#...#.#.#...#.#2#',
        '#.#.###.#.#.###.###.#',
        '#.#.#...#.#.#.......#',
        '#.###.#####.#######.#',
        '#.....#...#.....#.#.#',
        '#.#####.#.#.###.#.#.#',
        '#.#.....#.#...#.#.#.#',
        '#.#####.#.#####.#.#.#',
        '#.......#.......#...#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#...#...#.......#...#',
        '###.#.#.#######E#.#.#',
        '#.#.#.#.#..2..#...#.#',
        '#.#.#.#.#.###.#####.#',
        '#...#.#...#.#.....#.#',
        '#.###.#####.#####.#.#',
        '#.#...#...#.....#...#',
        '#.###.#.#.#.###.###.#',
        '#.....#.#.#...#...#.#',
        '#######.#.###.#3###.#',
        '#.......#...#.#.#...#',
        '###.#######.#.#.#.###',
        '#...#...#...#.#.#.#.#',
        '#.###.###.#####.#.#.#',
        '#.#.......P.....#...#',
        '#.#.###############.#',
        '#.#.3...#...........#',
        '#.#######.###########',
        '#...................#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#...#.............#.#',
        '###.#.#####.#####.#.#',
        '#.#.#.#...#.P...#...#',
        '#.#.#.#.#.#####.#####',
        '#...#.#.#.....#.....#',
        '#E###.#.#######.###.#',
        '#.#.....#.....#...#.#',
        '#.#######.###.###.#.#',
        '#.........#2..#...#.#',
        '###########.###.###.#',
        '#.......#.#.#.....#.#',
        '#.#####.#.#.#####.#.#',
        '#.#...#...#.....#.#.#',
        '#.###.#.#######.###.#',
        '#...#...#.....#.#..3#',
        '#.#.#####.###.#.#.###',
        '#.#.....#.#.#...#...#',
        '#.#####.#.#.#######.#',
        '#.....#3............#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#...#...........#...#',
        '###.#.#######.#.#.#.#',
        '#.#.#.#.....#.#...#.#',
        '#.#.#.#.#.###.#####.#',
        '#.#.#.#.#.#...#.....#',
        '#.#.#.#.#.#.###.#####',
        '#.#.#.#.#.#...#3....#',
        '#.#.#.###.###.#####.#',
        '#.#E#...#.2.#...#.#.#',
        '#.#.###.###.###.#.#.#',
        '#.#.#.#.....#...#P..#',
        '#.#.#.###.###.###.###',
        '#.#.#.....#...#...#.#',
        '#.#.#######3#####.#.#',
        '#.#.......#.....#.#.#',
        '#.#######.#####.#.#.#',
        '#.......#.#...#.#...#',
        '#.###.###.#.#.#.###.#',
        '#...#.......#...#...#',
        '#####################',
    ]),
]


def _rect(color):
    return [[color] * CELL for _ in range(CELL)]


def _gate_px(period, t):
    phase = t % period
    if phase == period - 1:
        # opens on the NEXT action -- show the open color as a hollow ring
        color = GATE_OPEN
        return [[color if r in (0, CELL - 1) or c in (0, CELL - 1) else 0
                 for c in range(CELL)] for r in range(CELL)]
    return _rect(PHASE_COLORS[phase % len(PHASE_COLORS)])


def _agent_px():
    px = [[0] * CELL for _ in range(CELL)]
    _fill_inner(px, AGENT)
    _fill_edge(px, 'top', AGENT)
    return px


def _parse(spec):
    walls, gates = set(), {}
    start = exit_cell = None
    for r, row in enumerate(spec["rows"]):
        for c, ch in enumerate(row):
            if ch == "#":
                walls.add((c, r))
            elif ch == "P":
                start = (c, r)
            elif ch == "E":
                exit_cell = (c, r)
            elif ch in ("2", "3"):
                gates[(c, r)] = int(ch)
    return walls, gates, start, exit_cell


def _build_level(index, spec):
    walls, gates, start, exit_cell = _parse(spec)
    sprites = []
    for (c, r) in walls:
        sprites.append(Sprite(_rect(WALL), name=f"wall_{r}_{c}", x=c * CELL, y=r * CELL,
                              blocking=BlockingMode.PIXEL_PERFECT, tags=["sys_static"]))
    for (c, r), k in gates.items():
        sprites.append(Sprite(_gate_px(k, 0), name=f"gate_{r}_{c}", x=c * CELL, y=r * CELL,
                              layer=1, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    sprites.append(Sprite(_rect(EXIT), name="exit", x=exit_cell[0] * CELL, y=exit_cell[1] * CELL,
                          layer=0, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    sprites.append(Sprite(_agent_px(), name="agent", x=start[0] * CELL, y=start[1] * CELL,
                          layer=3, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    return Level(sprites=sprites, grid_size=(GRID * CELL, GRID * CELL),
                 name=f"level_{index + 1}")


class Cl01(ARCBaseGame):
    def __init__(self, seed: int = 0, debug: bool = False):
        levels = [_build_level(i, spec) for i, spec in enumerate(LEVELS)]
        super().__init__(
            game_id="cl01",
            levels=levels,
            camera=Camera(width=GRID * CELL, height=GRID * CELL),
            debug=debug,
            available_actions=[1, 2, 3, 4, 5],
            seed=seed,
        )
        self._t = 0

    def on_set_level(self, level):
        self._t = 0

    def _atlas_reset_level_state(self):
        self._t = 0
        self._sync()

    def level_reset(self):
        super().level_reset()
        self._atlas_reset_level_state()

    def full_reset(self):
        super().full_reset()
        self._atlas_reset_level_state()

    def _sprite(self, name):
        found = self.current_level.get_sprites_by_name(name)
        return found[0] if found else None

    def _sync(self):
        spec = LEVELS[self.level_index]
        walls, gates, start, exit_cell = _parse(spec)
        for (c, r), k in gates.items():
            s = self._sprite(f"gate_{r}_{c}")
            if s is not None:
                px = _gate_px(k, self._t)
                for rr in range(CELL):
                    for cc in range(CELL):
                        s.pixels[rr][cc] = px[rr][cc]

    def step(self) -> None:
        spec = LEVELS[self.level_index]
        action = self.action.id
        if action == GameAction.RESET:
            self._sync()
            self.complete_action()
            return
        walls, gates, start, exit_cell = _parse(spec)
        agent = self._sprite("agent")
        if agent is None:
            self.complete_action()
            return
        c, r = agent.x // CELL, agent.y // CELL

        acted = False
        if action == GameAction.ACTION5:
            acted = True
        elif action in (GameAction.ACTION1, GameAction.ACTION2,
                        GameAction.ACTION3, GameAction.ACTION4):
            d = {GameAction.ACTION1: (0, -1), GameAction.ACTION2: (0, 1),
                 GameAction.ACTION3: (-1, 0), GameAction.ACTION4: (1, 0)}[action]
            nc, nr = c + d[0], r + d[1]
            blocked = (nc, nr) in walls or not (0 <= nc < GRID and 0 <= nr < GRID)
            if not blocked and (nc, nr) in gates:
                # the move lands on action count t+1: open iff (t+1) % k == 0
                if (self._t + 1) % gates[(nc, nr)] != 0:
                    blocked = True
            if not blocked:
                agent.set_position(nc * CELL, nr * CELL)
                if (nc, nr) == exit_cell:
                    self.next_level()
                    self.complete_action()
                    return
            acted = True
        if acted:
            self._t += 1
            self._sync()
        self.complete_action()
