# Original game for the atlas testbed (30.08.2026) -- NOT an ARC Prize game.
# "Conveyors" (cv01) -- rank-7 mechanic from the Gemini round-11 pool plan:
# one-way directed edges (external force vectors, no backtracking).
#
# Rules: ACTION1-4 move. Stepping onto an arrow tile forcibly slides the
# agent one cell in the arrow's direction, chaining across consecutive
# arrows. Arrows only work one way. Reach the exit pad.

from arcengine import (
    ARCBaseGame,
    BlockingMode,
    Camera,
    GameAction,
    Level,
    Sprite,
)

CELL = 3
GRID = 21


# --- pixel helpers, added 03.09 by scripts/cellify_sprites.py ---------------
# These replace literal pixel indices so the sprite renders at any CELL. The
# shapes are exactly what the literals drew at CELL == 4, which
# scripts/frame_fingerprint.py verifies by hashing every frame before and
# after the rewrite.

def _fill_inner(px, color):
    """Everything except the one-pixel border."""
    for _r in range(1, CELL - 1):
        for _c in range(1, CELL - 1):
            px[_r][_c] = color
    return px


def _fill_edge(px, side, color):
    """The middle stretch of one edge -- the part that is not a corner."""
    span = range(1, CELL - 1) if CELL > 2 else range(CELL)
    for _i in span:
        if side == "top":
            px[0][_i] = color
        elif side == "bottom":
            px[CELL - 1][_i] = color
        elif side == "left":
            px[_i][0] = color
        else:
            px[_i][CELL - 1] = color
    return px


def _fill_row(px, col, color):
    """The middle rows of one column."""
    for _r in range(1, CELL - 1):
        px[_r][col] = color
    return px

def _fill_edge_row(px, row, color):
    """The middle stretch of one row."""
    for _c in range(1, CELL - 1) if CELL > 2 else range(CELL):
        px[row][_c] = color
    return px


def _fill_edge_col(px, col, color):
    """The middle stretch of one column."""
    for _r in range(1, CELL - 1) if CELL > 2 else range(CELL):
        px[_r][col] = color
    return px


WALL = 9
AGENT = 3
EXIT = 4
ARROW = 11

ARROWS = {"^": (0, -1), "v": (0, 1), "<": (-1, 0), ">": (1, 0)}

# rows: '#'=wall, 'P'=agent, 'E'=exit, '^v<>'=conveyor arrows.
LEVELS = [
    # 03.09: regenerated by scripts/regen_short_levels.py on a full
    # 64x64 board (GRID 8 -> 16), nine levels along the public
    # difficulty curve. The old five levels cost 6-10 actions where the
    # public median level 1 is 30, so clearing them said nothing about
    # the games we are actually scored on -- and one of them (gv01)
    # shipped a level whose true optimum was a single action.
    # Every level below was PROVEN by BFS through the engine, never
    # counted by hand, and carries the objects of the level it replaces
    # in the same numbers.
    dict(rows=[
        '#####################',
        '#.#.........#......v#',
        '#.###.###.###.#####.#',
        '#...#...#.P^......#.#',
        '###.#####.#########.#',
        '#.#.#...#.#.........#',
        '#.#.#.#.#.#.#######.#',
        '#.#...#.#.#.#...#...#',
        '#.#####.###.#.#.#.###',
        '#...#...#...#.#.#.#.#',
        '#.#.#.###.###.###.#.#',
        '#.#.#.#..E#.....#.#.#',
        '#.###.#.###.###.#.#.#',
        '#.....#.#.#.#.#...#.#',
        '#.#####.#.#.#.#####.#',
        '#.....#.#...#...#...#',
        '#####.#.#.###.#.#.#.#',
        '#...#...#.#...#...#.#',
        '#.#######.#########.#',
        '#................v..#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#.........#.........#',
        '#########.#######.#.#',
        '#.....#.#....P..#.#.#',
        '#.###.#.#######.###.#',
        '#.#.....#...#...#...#',
        '#.#######.#.#.###.#.#',
        '#.....#...#.#.....#.#',
        '#.###.#.###.#######.#',
        '#...#E..#...#.....#.#',
        '###.#####.###.###.#.#',
        '#...#...#.....#.#...#',
        '#.#####.#######.#####',
        '#.....#.....#.......#',
        '#####.#.###.#.###.###',
        '#...#.#...#.....#...#',
        '#.###<#############.#',
        '#v..#...#....>#.....#',
        '#.#.###.#.###>#.###.#',
        '#.#.......#.....#...#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#.#.....#.#.^.....#.#',
        '#.#.###.#.#.#.###.#.#',
        '#...#...#.E.#.#...#.#',
        '#####.###.###.#.###.#',
        '#...#...#.#...#.#...#',
        '#.#####.###.###.###.#',
        '#P#.....#^..#.#.....#',
        '#.#.#####.###.#####.#',
        '#.#....v#.#.....#...#',
        '#.#####.#.#.#####.###',
        '#.....#...#.......#^#',
        '#.###.#####.#######.#',
        '#.#.#.......#.......#',
        '#.#.###########.###.#',
        '#.#...........#.#...#',
        '#.###.#.#####.#.#.###',
        '#...#.#v..#.#.#.#.#.#',
        '###.#####.#.#.#.#.#.#',
        '#.........#.....#...#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#...#.....#.....#...#',
        '###.#.#.###.#.#.#.#.#',
        '#.#.#.#.#...#.#.#.#.#',
        '#.#.#.#.#.###.#.###<#',
        '#.#.#E#.....#.#...#.#',
        '#.#.###.#####.###.#.#',
        '#.#>..#.#...#...#...#',
        '#.###.#.#.#.###.###.#',
        '#...#.#.#.#.....#.#.#',
        '#.###.###.#######.#.#',
        '#....<#...#.......#.#',
        '#.#####.###.#.#####.#',
        '#.#..>..#...#..v....#',
        '#.###.#.#####.#######',
        '#...#.#.....#...#.P.#',
        '###.#.#####.###.#.#.#',
        '#.#.#.#...#.#.#...#.#',
        '#.#.###.#.#.#.#####.#',
        '#.......#...#.^.....#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#^..#.............#.#',
        '###.###########.#.#.#',
        '#.#.#.......#.>.#.#.#',
        '#.#.#.#####.#.###.#.#',
        '#.#.#.#...#^..#.#.P.#',
        '#.#.#<###.#####.###.#',
        '#.#...#.....#.....#.#',
        '#.#####.#.###.###.#.#',
        '#.......#.#...#...#.#',
        '#.###.#####.###.###.#',
        '#...#...#...#.#.....#',
        '###.###.#.###.#######',
        '#.#...#.#.......#.<.#',
        '#.###.#.#######.#.###',
        '#.#...#....v..#.#v..#',
        '#.#.#########.#.###.#',
        '#.#...#E..#...#.#...#',
        '#.###.###.#.###.#.#.#',
        '#.........#.......#.#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#...#........<....#.#',
        '###.#.#####.#####.#.#',
        '#.#.#.#...#.P...#...#',
        '#.#.#.#.#.#####.#####',
        '#...#.#.#.....#.....#',
        '#E###.#.#######.###.#',
        '#.#.....#.....#...#.#',
        '#^#######.###.###.#.#',
        '#.........#>..#...#.#',
        '###########.###.###.#',
        '#.......#.#.#.....#.#',
        '#.#####.#.#.#####.#.#',
        '#.#...#...#.....#.#.#',
        '#.###<#.#######.###.#',
        '#.^.#...#.....#.#..v#',
        '#.#.#####.###.#.#.###',
        '#.#.....#.#.#...#...#',
        '#.#####.#.#.#######.#',
        '#.....#v............#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#.....#.v...#.......#',
        '#####.###.#.#.#####.#',
        '#.....#...#.#.....#.#',
        '#.#####.###.#####.#.#',
        '#.#.....#.#.#..<..#.#',
        '#E#####.#.#.#######.#',
        '#.<...#.#>#.#.......#',
        '#####.#.#.#.#.#####.#',
        '#.#...#.#..P.^#...#.#',
        '#.#.###.#######.#.#.#',
        '#.#.#...#...#...#.#.#',
        '#.#.#.###.#.#####.#.#',
        '#...#.#...#...#.v.#.#',
        '#.###.#.#####.#.###.#',
        '#.#.....#...#.#...#.#',
        '#.#######.#.#.#.#.#.#',
        '#.....#...#...#.#.#.#',
        '#####.#.#######.#.#.#',
        '#^......#.......#...#',
        '#####################',
    ]),
    dict(rows=[
        '#####################',
        '#..P#.....#.#.....<.#',
        '###.#.###.#.#.#####.#',
        '#...#...#v..#.#.....#',
        '#.###.#.#####E#.#####',
        '#v#.#.#.....#.#.....#',
        '#.#.#.#####.#.#####.#',
        '#.#.#...#.#...#.^.#.#',
        '#.#.###.#.#####.#.#.#',
        '#.#.........#...#.#.#',
        '#.###.#####.#.###.#.#',
        '#...#.#...#...#..<#.#',
        '###.###.#.#####.###.#',
        '#.^.#...#...#...#...#',
        '#.###.#####.#####.#.#',
        '#.#.......#.......#>#',
        '#.#.#####.#########.#',
        '#.#...#...#.......#.#',
        '#.#####.###.#######.#',
        '#.......#...........#',
        '#####################',
    ]),
]


def _rect(color):
    return [[color] * CELL for _ in range(CELL)]


def _arrow_px(d):
    px = [[0] * CELL for _ in range(CELL)]
    dx, dy = d
    if dy == -1:
        _fill_edge(px, 'top', ARROW)
        px[1][0] = px[1][CELL - 1] = ARROW
        _fill_edge_row(px, CELL - 2, ARROW)
    elif dy == 1:
        _fill_edge(px, 'bottom', ARROW)
        px[CELL - 2][0] = px[CELL - 2][CELL - 1] = ARROW
        _fill_edge_row(px, 1, ARROW)
    elif dx == -1:
        _fill_edge(px, 'left', ARROW)
        px[0][1] = px[CELL - 1][1] = ARROW
        _fill_edge_col(px, CELL - 2, ARROW)
    else:
        _fill_edge(px, 'right', ARROW)
        px[0][CELL - 2] = px[CELL - 1][CELL - 2] = ARROW
        _fill_edge_col(px, 1, ARROW)
    return px


def _agent_px():
    px = [[0] * CELL for _ in range(CELL)]
    _fill_inner(px, AGENT)
    _fill_edge(px, 'top', AGENT)
    return px


def _parse(spec):
    walls, arrows = set(), {}
    start = exit_cell = None
    for r, row in enumerate(spec["rows"]):
        for c, ch in enumerate(row):
            if ch == "#":
                walls.add((c, r))
            elif ch == "P":
                start = (c, r)
            elif ch == "E":
                exit_cell = (c, r)
            elif ch in ARROWS:
                arrows[(c, r)] = ARROWS[ch]
    return walls, arrows, start, exit_cell


def slide(pos, walls, arrows):
    """Chain conveyor pushes (max 8 to stay finite on generated loops)."""
    c, r = pos
    for _ in range(8):
        if (c, r) not in arrows:
            break
        dx, dy = arrows[(c, r)]
        nc, nr = c + dx, r + dy
        if (nc, nr) in walls or not (0 <= nc < GRID and 0 <= nr < GRID):
            break
        c, r = nc, nr
    return (c, r)


def _build_level(index, spec):
    walls, arrows, start, exit_cell = _parse(spec)
    sprites = []
    for (c, r) in walls:
        sprites.append(Sprite(_rect(WALL), name=f"wall_{r}_{c}", x=c * CELL, y=r * CELL,
                              blocking=BlockingMode.PIXEL_PERFECT, tags=["sys_static"]))
    for (c, r), d in arrows.items():
        sprites.append(Sprite(_arrow_px(d), name=f"arrow_{r}_{c}", x=c * CELL, y=r * CELL,
                              layer=1, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    sprites.append(Sprite(_rect(EXIT), name="exit", x=exit_cell[0] * CELL, y=exit_cell[1] * CELL,
                          layer=0, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    sprites.append(Sprite(_agent_px(), name="agent", x=start[0] * CELL, y=start[1] * CELL,
                          layer=3, blocking=BlockingMode.NOT_BLOCKED, collidable=False))
    return Level(sprites=sprites, grid_size=(GRID * CELL, GRID * CELL),
                 name=f"level_{index + 1}")


class Cv01(ARCBaseGame):
    def __init__(self, seed: int = 0, debug: bool = False):
        levels = [_build_level(i, spec) for i, spec in enumerate(LEVELS)]
        super().__init__(
            game_id="cv01",
            levels=levels,
            camera=Camera(width=GRID * CELL, height=GRID * CELL),
            debug=debug,
            available_actions=[1, 2, 3, 4],
            seed=seed,
        )

    def _atlas_reset_level_state(self):
        pass

    def level_reset(self):
        super().level_reset()
        self._atlas_reset_level_state()

    def full_reset(self):
        super().full_reset()
        self._atlas_reset_level_state()

    def _sprite(self, name):
        found = self.current_level.get_sprites_by_name(name)
        return found[0] if found else None

    def step(self) -> None:
        spec = LEVELS[self.level_index]
        action = self.action.id
        if action == GameAction.RESET:
            self.complete_action()
            return
        walls, arrows, start, exit_cell = _parse(spec)
        agent = self._sprite("agent")
        if agent is None:
            self.complete_action()
            return
        c, r = agent.x // CELL, agent.y // CELL

        if action in (GameAction.ACTION1, GameAction.ACTION2,
                      GameAction.ACTION3, GameAction.ACTION4):
            d = {GameAction.ACTION1: (0, -1), GameAction.ACTION2: (0, 1),
                 GameAction.ACTION3: (-1, 0), GameAction.ACTION4: (1, 0)}[action]
            nc, nr = c + d[0], r + d[1]
            if (nc, nr) not in walls and 0 <= nc < GRID and 0 <= nr < GRID:
                nc, nr = slide((nc, nr), walls, arrows)
                agent.set_position(nc * CELL, nr * CELL)
                if (nc, nr) == exit_cell:
                    self.next_level()
        self.complete_action()
